# Start from a Debian image with the latest version of Go installed
# and a workspace (GOPATH) configured at /go.
FROM golang

# Include some dependencies
RUN go get cloud.google.com/go/datastore
RUN go get github.com/satori/go.uuid

